from enum import StrEnum

class ProjectStatus(StrEnum):
    CREATED="CREATED"
    ANALYZING="ANALYZING"
    PLANNING="PLANNING"
    READY="READY"
    RUNNING="RUNNING"
    VALIDATING="VALIDATING"
    REVIEWING="REVIEWING"
    COMPLETING="COMPLETING"
    COMPLETED="COMPLETED"
    BLOCKED="BLOCKED"
    FAILED="FAILED"
    CANCELLED="CANCELLED"

class TaskStatus(StrEnum):
    CREATED="CREATED"
    READY="READY"
    RUNNING="RUNNING"
    COMPLETED="COMPLETED"
    FAILED="FAILED"

class RunStatus(StrEnum):
    CREATED="CREATED"
    RUNNING="RUNNING"
    COMPLETED="COMPLETED"
    FAILED="FAILED"

class EvidenceType(StrEnum):
    PLAN="PLAN"
    BUILD_RESULT="BUILD_RESULT"
    TEST_RESULT="TEST_RESULT"
